import { ArrowRight, BookOpenCheck, Check, ChevronRight, Circle, Clock3, Code2, LockKeyhole, Map, Minus, Play, Plus, Sparkles, Target, Trophy, Users, Zap } from 'lucide-react';
import { useMemo, useState, type ReactNode } from 'react';
import { Link } from 'wouter';
import { useProgress } from '@/context/progress-context';

type NodeStatus = 'locked' | 'available' | 'in-progress' | 'completed';
type Question = { title: string; prompt: string; starter: string; input: string; expected: unknown };
type SkillNode = { id: string; title: string; lane: string; description: string; duration: string; xp: number; prerequisites: string[]; icon: typeof Code2; learn: string; subtopics: string[]; questions: Question[] };

const lanes = [
  { id: 'signal', label: 'DSA foundations', color: 'cyan' },
  { id: 'craft', label: 'Core structures', color: 'purple' },
  { id: 'proof', label: 'Advanced patterns', color: 'yellow' },
];

const q = (title: string, prompt: string, starter: string, input: string, expected: unknown): Question => ({ title, prompt, starter, input, expected });
const nodes: SkillNode[] = [
  { id: 'basics', title: 'Basics', lane: 'signal', description: 'Build the habits that make every data-structure problem easier to reason about.', duration: '20 min', xp: 120, prerequisites: [], icon: Sparkles, learn: 'Big-O complexity, variables, loops, and how to trace an algorithm.', subtopics: ['Time and space complexity', 'Two-pointer thinking', 'Dry runs and edge cases'], questions: [q('Find the maximum', 'Return the largest number in an array.', 'function solve(nums) {\\n  // return the largest number\\n}', '[3, 8, 2, 9]', 9)] },
  { id: 'arrays-strings', title: 'Arrays & Strings', lane: 'signal', description: 'Use indexing, windows, and pointers to solve the most common interview patterns.', duration: '28 min', xp: 150, prerequisites: ['basics'], icon: Code2, learn: 'Array traversal, prefix sums, sliding windows, and string manipulation.', subtopics: ['Sliding window', 'Two pointers', 'Prefix sums'], questions: [q('Two sum', 'Return the indices of two numbers that add up to target.', 'function solve(nums, target) {\\n  // return [leftIndex, rightIndex]\\n}', '[2, 7, 11, 15], 9', [0, 1]) ] },
  { id: 'linked-lists', title: 'Linked Lists', lane: 'craft', description: 'Learn to move through and reshape pointer-based data structures safely.', duration: '26 min', xp: 180, prerequisites: ['arrays-strings'], icon: Map, learn: 'Nodes, pointers, reversal, and fast/slow traversal.', subtopics: ['Reverse a list', 'Fast and slow pointers', 'Merging lists'], questions: [q('Reverse an array', 'Return the values in reverse order (a pointer warm-up).', 'function solve(nums) {\\n  // return the reversed values\\n}', '[1, 2, 3, 4]', [4, 3, 2, 1]) ] },
  { id: 'stacks-queues', title: 'Stacks & Queues', lane: 'craft', description: 'Choose the right order of processing for nested and breadth-first problems.', duration: '25 min', xp: 180, prerequisites: ['arrays-strings'], icon: Code2, learn: 'LIFO and FIFO behavior, monotonic stacks, and queue simulation.', subtopics: ['Valid parentheses', 'Monotonic stack', 'BFS queues'], questions: [q('Valid brackets', 'Return true when every opening bracket is closed in order.', 'function solve(text) {\\n  // return true or false\\n}', '`([])`', true)] },
  { id: 'hashing', title: 'Hashing', lane: 'craft', description: 'Trade memory for fast lookups and recognize counting patterns quickly.', duration: '24 min', xp: 180, prerequisites: ['arrays-strings'], icon: Target, learn: 'Maps, sets, frequency counting, and constant-time lookup strategies.', subtopics: ['Frequency maps', 'Sets for duplicates', 'Lookup complements'], questions: [q('Contains duplicate', 'Return true if any value appears more than once.', 'function solve(nums) {\\n  // return true or false\\n}', '[1, 2, 3, 1]', true)] },
  { id: 'recursion-backtracking', title: 'Recursion & Backtracking', lane: 'proof', description: 'Break a problem into smaller calls and explore choices without losing state.', duration: '35 min', xp: 220, prerequisites: ['stacks-queues', 'hashing'], icon: Sparkles, learn: 'Base cases, recursion trees, choices, and undo steps.', subtopics: ['Base cases', 'Subsets and permutations', 'Constraint pruning'], questions: [q('Factorial', 'Return n factorial using recursion.', 'function solve(n) {\\n  // return n!\\n}', '5', 120)] },
  { id: 'trees', title: 'Trees', lane: 'proof', description: 'Traverse hierarchical data and turn recursive structure into reliable solutions.', duration: '35 min', xp: 240, prerequisites: ['recursion-backtracking'], icon: Trophy, learn: 'DFS, BFS, binary-search-tree rules, and tree height.', subtopics: ['Preorder traversal', 'Level order traversal', 'BST search'], questions: [q('Tree height', 'Return the height of a tree represented as nested arrays.', 'function solve(tree) {\\n  // tree is [value, left, right]\\n  if (!tree) return 0;\\n}', '[1, [2, null, null], [3, null, null]]', 2)] },
  { id: 'heaps', title: 'Heaps', lane: 'proof', description: 'Keep the smallest or largest candidates available while processing a stream.', duration: '28 min', xp: 220, prerequisites: ['trees'], icon: BookOpenCheck, learn: 'Priority queues, heap invariants, and top-k selection.', subtopics: ['Min and max heaps', 'Top K elements', 'Merge sorted data'], questions: [q('Top value', 'Return the largest value in an array.', 'function solve(nums) {\\n  // heap warm-up\\n}', '[4, 1, 7, 2]', 7)] },
  { id: 'graphs', title: 'Graphs', lane: 'proof', description: 'Model relationships and navigate them with systematic search.', duration: '40 min', xp: 280, prerequisites: ['trees', 'heaps'], icon: Map, learn: 'Adjacency lists, BFS, DFS, visited sets, and shortest paths.', subtopics: ['BFS and DFS', 'Connected components', 'Shortest path intuition'], questions: [q('Reachable nodes', 'Count nodes reachable from node 0 in an adjacency list.', 'function solve(graph) {\\n  // return the count\\n}', '[[1], [0, 2], [1]]', 3)] },
  { id: 'dynamic-programming', title: 'Dynamic Programming', lane: 'proof', description: 'Turn repeated subproblems into efficient solutions with clear state.', duration: '45 min', xp: 320, prerequisites: ['graphs'], icon: Trophy, learn: 'State design, transitions, memoization, and bottom-up tables.', subtopics: ['1D DP', 'Memoization', 'Choosing a state'], questions: [q('Climbing stairs', 'You can climb 1 or 2 steps. Return the number of ways to reach n.', 'function solve(n) {\\n  // return the number of ways\\n}', '5', 8)] },
];

export default function InterviewRoadmap() {
  const progressState = useProgress();
  const [completed, setCompleted] = useState<string[]>(() => JSON.parse(localStorage.getItem('dsa-completed') ?? '[]'));
  const [started, setStarted] = useState<string[]>(['basics']);
  const [selectedId, setSelectedId] = useState('basics');
  const [selectedQuestion, setSelectedQuestion] = useState(0);
  const [code, setCode] = useState(nodes[0].questions[0].starter);
  const [output, setOutput] = useState('');
  const [zoom, setZoom] = useState(1);
  const selected = nodes.find(node => node.id === selectedId) ?? nodes[0];
  const question = selected.questions[selectedQuestion] ?? selected.questions[0];
  const SelectedIcon = selected.icon;
  const statusFor = (node: SkillNode): NodeStatus => completed.includes(node.id) ? 'completed' : started.includes(node.id) ? 'in-progress' : node.prerequisites.every(id => completed.includes(id)) ? 'available' : 'locked';
  const progress = Math.round((completed.length / nodes.length) * 100);
  const nextNode = useMemo(() => nodes.find(node => statusFor(node) === 'available') ?? nodes.find(node => statusFor(node) === 'in-progress'), [completed, started]);
  const selectNode = (id: string) => { setSelectedId(id); setSelectedQuestion(0); setCode(nodes.find(node => node.id === id)?.questions[0].starter ?? ''); setOutput(''); };
  const toggleSelected = () => {
    if (statusFor(selected) === 'locked') return;
    setStarted(items => items.includes(selected.id) ? items : [...items, selected.id]);
    setCompleted(items => { const reopening = items.includes(selected.id); const next = reopening ? items.filter(id => id !== selected.id) : [...items, selected.id]; localStorage.setItem('dsa-completed', JSON.stringify(next)); if (!reopening) { progressState.completeRoadmapNode(selected.id, selected.title); progressState.addXP(selected.xp, `completed ${selected.title}`, `roadmap:${selected.id}`); progressState.addCoins(Math.round(selected.xp / 10), `completed ${selected.title}`, `roadmap-coins:${selected.id}`); } return next; });
  };
  const runCode = () => {
    try {
      const result = new Function(`${code}; return solve(${question.input});`)();
      const correct = JSON.stringify(result) === JSON.stringify(question.expected);
      progressState.recordQuestion(selected.title, correct);
       if (correct) progressState.addXP(5, `correct answer in ${selected.title}`, `roadmap-question-correct:${selected.id}:${selectedQuestion}`);
      setOutput(correct ? `✓ Accepted\\nOutput: ${JSON.stringify(result)}` : `✗ Try again\\nOutput: ${JSON.stringify(result)}\\nExpected: ${JSON.stringify(question.expected)}`);
    } catch (error) { setOutput(`⚠ ${error instanceof Error ? error.message : 'Could not run code'}`); }
  };

  return <div className="stagger space-y-7">
    <div className="retro-page-header flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-accent"><span className="mr-2 text-primary/40">05</span>DSA prep roadmap</div><h1 className="text-3xl font-semibold tracking-[-.055em] sm:text-[2.6rem]">Build the interview loadout.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">Follow the tree, pick a question, and make the solution pass.</p></div><Link data-testid="link-roadmap-mock-interview" href="/mock-interview" className="button-primary"><Play size={15} /> Run a mock</Link></div>
    <section className="roadmap-progress retro-card"><div><p className="pixel-label text-foreground/55">Current build / DSA path</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Your problem-solving tree is growing.</h2><p className="mt-2 max-w-lg text-sm text-muted-foreground">Complete one topic to unlock the next branch.</p></div><div className="roadmap-progress-score"><span data-testid="text-roadmap-progress">{progress}%</span><small>{completed.length} / {nodes.length} topics</small></div><div className="roadmap-progress-bar"><div style={{ width: `${progress}%` }} /></div></section>
    <section className="roadmap-shell"><div className="roadmap-toolbar"><div className="flex items-center gap-2"><Map size={16} className="text-accent" /><span className="font-mono text-[10px] uppercase tracking-[.18em]">DSA tree / zoom {Math.round(zoom * 100)}%</span></div><div className="flex items-center gap-1"><button data-testid="button-roadmap-zoom-out" aria-label="Zoom out skill tree" onClick={() => setZoom(value => Math.max(.78, Number((value - .1).toFixed(2))))} className="roadmap-zoom"><Minus size={15} /></button><button data-testid="button-roadmap-zoom-reset" onClick={() => setZoom(1)} className="roadmap-zoom text-[10px]">Reset</button><button data-testid="button-roadmap-zoom-in" aria-label="Zoom in skill tree" onClick={() => setZoom(value => Math.min(1.25, Number((value + .1).toFixed(2))))} className="roadmap-zoom"><Plus size={15} /></button></div></div><div className="roadmap-scroll" aria-label="DSA learning tree"><div className="roadmap-canvas" style={{ transform: `scale(${zoom})` }}>{lanes.map(lane => <div key={lane.id} className={`roadmap-lane roadmap-lane-${lane.color}`}><div className="roadmap-lane-label">{lane.label}</div>{nodes.filter(node => node.lane === lane.id).map(node => <SkillTreeNode key={node.id} node={node} status={statusFor(node)} selected={selected.id === node.id} onSelect={() => selectNode(node.id)} />)}</div>)}</div></div><p className="roadmap-scroll-hint">Scroll sideways to inspect the full map on smaller screens.</p></section>
    <div className="grid gap-4 lg:grid-cols-[1fr_.76fr]"><section className="roadmap-detail retro-card"><div className="flex items-start justify-between gap-4"><div><div className={`roadmap-status roadmap-status-${statusFor(selected)}`}><StatusIcon status={statusFor(selected)} /> {statusFor(selected).replace('-', ' ')}</div><h2 data-testid={`text-roadmap-node-${selected.id}`} className="mt-4 text-3xl font-semibold tracking-[-.05em]">{selected.title}</h2><p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">{selected.description}</p></div><SelectedIcon size={26} className="shrink-0 text-accent" /></div><div className="mt-7 grid grid-cols-2 gap-3 sm:max-w-sm"><div className="roadmap-detail-stat"><Clock3 size={14} /> {selected.duration}</div><div className="roadmap-detail-stat"><Zap size={14} /> +{selected.xp} XP</div></div><div className="mt-7 space-y-5 border-t border-border pt-6"><div><p className="pixel-label text-foreground/55">What to learn</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{selected.learn}</p></div><div><p className="pixel-label text-foreground/55">Key subtopics</p><div className="mt-2 flex flex-wrap gap-2">{selected.subtopics.map(topic => <span key={topic} className="rounded-md bg-muted px-2.5 py-1.5 text-xs">{topic}</span>)}</div></div><div><p className="pixel-label text-foreground/55">Recommended practice</p><div className="mt-2 flex flex-wrap gap-2">{selected.questions.map((item, index) => <button key={item.title} onClick={() => { setSelectedQuestion(index); setCode(item.starter); setOutput(''); }} className={`rounded-md border px-3 py-2 text-left text-xs ${selectedQuestion === index ? 'border-accent bg-accent/15' : 'border-border bg-card'}`}>{item.title}</button>)}</div></div><button data-testid={`button-toggle-roadmap-node-${selected.id}`} disabled={statusFor(selected) === 'locked'} onClick={toggleSelected} className={statusFor(selected) === 'completed' ? 'button-secondary' : 'button-primary'}>{statusFor(selected) === 'completed' ? <><Check size={15} /> Reopen topic</> : <><Check size={15} /> Complete topic</>}</button></div></section><aside className="roadmap-next retro-side-card"><p className="pixel-label text-foreground/55">Guidance / next skill</p><div className="mt-5 grid h-11 w-11 place-items-center border-2 border-accent bg-accent text-primary shadow-[3px_3px_0_var(--retro-ink)]"><ChevronRight size={20} /></div><h2 className="mt-5 text-xl font-semibold">{nextNode?.title ?? 'Tree complete'}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{nextNode ? `Unlock ${nextNode.title.toLowerCase()} by completing the current topic.` : 'Your DSA path is fully unlocked.'}</p><Link data-testid="link-roadmap-practice" href="/practice" className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-primary">Open practice lab <ArrowRight size={14} /></Link></aside></div>
    <section className="retro-card"><div className="mb-5 flex items-center justify-between gap-3"><div><p className="pixel-label text-foreground/55">Practice / {selected.title}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{question.title}</h2></div><Code2 size={22} className="text-accent" /></div><p className="mb-5 text-sm leading-relaxed text-muted-foreground">{question.prompt}</p><textarea aria-label="Code editor" value={code} onChange={event => setCode(event.target.value)} spellCheck={false} className="min-h-52 w-full rounded-md border border-border bg-primary p-4 font-mono text-sm leading-relaxed text-primary-foreground outline-none focus:border-accent" /><div className="mt-4 flex flex-wrap items-center gap-3"><button data-testid="button-run-code" onClick={runCode} className="button-primary"><Play size={15} /> Run code</button><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Input: {question.input}</span></div>{output && <pre data-testid="text-code-output" className="mt-4 whitespace-pre-wrap rounded-md border border-border bg-muted/45 p-4 font-mono text-xs">{output}</pre>}</section>
  </div>;
}

function SkillTreeNode({ node, status, selected, onSelect }: { node: SkillNode; status: NodeStatus; selected: boolean; onSelect: () => void }) {
  const Icon = node.icon;
  return <button data-testid={`button-roadmap-node-${node.id}`} aria-pressed={selected} aria-label={`${node.title}, ${status}`} onClick={onSelect} className={`skill-node skill-node-${status} ${selected ? 'skill-node-selected' : ''}`}><span className="skill-node-icon">{status === 'completed' ? <Check size={17} /> : status === 'locked' ? <LockKeyhole size={15} /> : <Icon size={17} />}</span><span className="min-w-0 text-left"><strong>{node.title}</strong><small>{status === 'completed' ? 'cleared' : status === 'locked' ? 'locked' : node.duration}</small></span><span className="skill-node-dot" /></button>;
}

function StatusIcon({ status }: { status: NodeStatus }) { if (status === 'completed') return <Check size={12} />; if (status === 'locked') return <LockKeyhole size={12} />; return <Circle size={10} />; }
function RoadmapTip({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="retro-card"><div className="mb-5 grid h-9 w-9 place-items-center rounded-md bg-accent/15 text-accent-foreground">{icon}</div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>; }