import { useEffect, useRef, useState, type ChangeEvent, type DragEvent } from 'react';
import { AlertCircle, ArrowRight, Check, FileCheck2, FileText, Lightbulb, Loader2, RefreshCw, Target, Upload, X } from 'lucide-react';
import { Link } from 'wouter';
import { analyzeResume, extractPdfText, formatFileSize, type ResumeFileMeta, type ResumeResult } from '@/lib/resume-analysis';

const STORAGE_KEY = 'final-boss-latest-resume-analysis';
type Status = 'idle' | 'reading' | 'ready' | 'error' | 'unsupported';

function ScoreBar({ score, tone = 'yellow' }: { score: number; tone?: 'yellow' | 'teal' }) {
  return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`${tone === 'teal' ? 'bg-[#287d78]' : 'bg-accent'} h-full rounded-full transition-all duration-700`} style={{ width: `${score}%` }} /></div>;
}

function UploadBox({ onPick, onDrop }: { onPick: () => void; onDrop: (event: DragEvent<HTMLDivElement>) => void }) {
  return <div className="relative flex min-h-[230px] flex-col items-center justify-center overflow-hidden rounded-xl border border-dashed border-primary/45 bg-primary/[.045] px-6 py-9 text-center transition-colors hover:bg-primary/[.08]" onClick={onPick} onDragOver={(event) => event.preventDefault()} onDrop={onDrop} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onPick(); }}>
    <div className="absolute -right-8 -top-8 h-32 w-32 rounded-full border border-accent/50 bg-accent/20" />
    <div className="relative mb-4 grid h-12 w-12 place-items-center rounded-xl bg-primary text-primary-foreground"><Upload size={21} /></div>
    <p className="relative text-lg font-semibold">Drop your resume here</p>
    <p className="relative mt-1 max-w-md text-sm text-muted-foreground">PDF works best. We’ll read it locally and show you what to sharpen.</p>
    <button type="button" onClick={(event) => { event.stopPropagation(); onPick(); }} className="button-primary relative mt-5"><Upload size={15} /> Choose a PDF</button>
    <p className="relative mt-3 font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">PDF only · max 10 MB · local-only</p>
  </div>;
}

function FileStatus({ meta, status, error, onReplace, onRetry }: { meta: ResumeFileMeta; status: Status; error: string | null; onReplace: () => void; onRetry: () => void }) {
  return <div className={`rounded-xl border p-5 ${error ? 'border-destructive/35 bg-destructive/[.04]' : 'border-border bg-card'}`}>
    <div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><FileText size={20} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold" data-testid="text-resume-filename">{meta.name}</p>{status === 'reading' && <span className="inline-flex items-center gap-1 rounded-full bg-accent/40 px-2 py-1 font-mono text-[9px] uppercase tracking-wider"><Loader2 size={11} className="animate-spin" /> Reading</span>}{status === 'ready' && <span className="inline-flex items-center gap-1 rounded-full bg-[#287d78]/15 px-2 py-1 font-mono text-[9px] uppercase tracking-wider text-[#287d78]"><Check size={11} /> Analyzed</span>}{error && <span className="inline-flex items-center gap-1 rounded-full bg-destructive/10 px-2 py-1 font-mono text-[9px] uppercase tracking-wider text-destructive"><AlertCircle size={11} /> Needs attention</span>}</div><p className="mt-1 font-mono text-[10px] text-muted-foreground" data-testid="text-resume-filesize">{formatFileSize(meta.size)} / PDF</p></div><button type="button" onClick={onReplace} aria-label="Replace resume" className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><X size={15} /></button></div>
    {status === 'reading' && <div className="mt-5"><div className="mb-2 flex justify-between font-mono text-[10px] uppercase tracking-wider text-muted-foreground"><span>Mapping your signal</span><span>Working</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full w-1/2 animate-pulse rounded-full bg-accent" /></div></div>}
    {error && <div className="mt-4 flex items-start gap-2 rounded-lg bg-destructive/10 p-3 text-sm text-destructive" role="alert" data-testid="status-parse-error"><AlertCircle size={16} className="mt-0.5 shrink-0" /><div><p>{error}</p><button type="button" onClick={onRetry} className="mt-2 inline-flex items-center gap-1 font-semibold underline"><RefreshCw size={13} /> Try again</button></div></div>}
  </div>;
}

function Results({ result, onReplace, onReanalyze }: { result: ResumeResult; onReplace: () => void; onReanalyze: () => void }) {
  return <div className="stagger space-y-4" data-testid="resume-results">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">Analysis complete</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em]">Here’s the useful part.</h2></div><div className="flex gap-2"><button type="button" onClick={onReanalyze} className="button-secondary"><RefreshCw size={14} /> Re-analyze</button><button type="button" onClick={onReplace} className="button-primary"><Upload size={14} /> Replace resume</button></div></div>
    <section className="grid gap-4 md:grid-cols-[.72fr_1.28fr]"><div className="rounded-xl bg-primary p-6 text-primary-foreground"><div className="mb-8 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.18em] text-primary-foreground/55">Resume readiness</span><FileCheck2 size={18} className="text-accent" /></div><div className="mb-2 text-7xl font-semibold tracking-[-.08em]" data-testid="text-resume-score">{result.score}<span className="text-2xl text-accent">/100</span></div><p className="max-w-xs text-sm leading-relaxed text-primary-foreground/65">{result.summary}</p><div className="mt-8"><ScoreBar score={result.score} tone="teal" /></div><p className="mt-3 font-mono text-[10px] text-primary-foreground/45">Analyzed {new Date(result.file.analyzedAt).toLocaleDateString()}</p></div><div className="rounded-xl border border-border bg-card p-6"><div className="mb-5 flex items-center justify-between"><h3 className="font-semibold">What shaped the score</h3><Target size={18} className="text-accent" /></div><div className="grid gap-5 sm:grid-cols-2">{result.contributors.map((item) => <div key={item.label}><div className="mb-2 flex justify-between text-sm"><span>{item.label}</span><span className="font-mono text-xs">{item.score}/100</span></div><ScoreBar score={item.score} tone={item.tone === 'good' ? 'teal' : 'yellow'} /><p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{item.note}</p></div>)}</div></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-foreground p-6 text-background"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-accent">Detected toolkit</p><h3 className="mt-2 text-xl font-semibold">Your technical signal</h3><p className="mt-1 text-sm leading-relaxed text-background/65">Skills found in the extracted text.</p><div className="mt-5 flex flex-wrap gap-2" data-testid="list-detected-skills">{result.skills.length ? result.skills.map((skill) => <span key={skill} className="rounded-md border border-background/15 bg-background/10 px-2.5 py-1.5 font-mono text-[11px]">{skill}</span>) : <span className="text-sm text-background/65">No common CS skills detected yet.</span>}</div></div><div className="rounded-xl border border-border bg-card p-6"><div className="mb-4 flex items-center gap-2"><Check size={16} className="text-[#287d78]" /><h3 className="font-semibold">What is already working</h3></div><ul className="space-y-3">{result.strengths.map((item, index) => <li key={item} data-testid={`resume-strength-${index}`} className="flex gap-3 text-sm leading-relaxed"><span className="mt-1 grid h-4 w-4 shrink-0 place-items-center rounded-full bg-[#287d78]/15 text-[#287d78]"><Check size={11} /></span>{item}</li>)}</ul></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card p-6"><div className="mb-4 flex items-center gap-2"><AlertCircle size={16} className="text-destructive" /><h3 className="font-semibold">Needs improvement</h3></div>{result.weaknesses.length ? <ul className="space-y-3">{result.weaknesses.map((item, index) => <li key={item} data-testid={`resume-weakness-${index}`} className="flex gap-3 text-sm leading-relaxed"><span className="mt-1 text-destructive">↗</span>{item}</li>)}</ul> : <p className="text-sm text-muted-foreground">No major gaps surfaced.</p>}</div><div className="rounded-xl border border-border bg-card p-6"><div className="mb-4 flex items-center gap-2"><Lightbulb size={16} className="text-accent" /><h3 className="font-semibold">Your next 3 moves</h3></div><ol className="space-y-4">{result.recommendations.map((item, index) => <li key={item.title} className="flex gap-3" data-testid={`resume-recommendation-${index}`}><span className="font-mono text-xs font-bold text-primary">0{index + 1}</span><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{item.body}</p></div></li>)}</ol></div></section>
  </div>;
}

export default function ResumeAnalyzer() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [status, setStatus] = useState<Status>('idle');
  const [error, setError] = useState<string | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [meta, setMeta] = useState<ResumeFileMeta | null>(null);
  const [result, setResult] = useState<ResumeResult | null>(null);
  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { const parsed = JSON.parse(saved) as ResumeResult; if (parsed.version === 1) { setResult(parsed); setMeta(parsed.file); setStatus('ready'); } } } catch { localStorage.removeItem(STORAGE_KEY); } }, []);
  const pick = () => inputRef.current?.click();
  const processFile = async (selected: File) => {
    setError(null); setFile(selected); setResult(null);
    const nextMeta = { name: selected.name, size: selected.size, type: selected.type, analyzedAt: new Date().toISOString() };
    setMeta(nextMeta);
    if (selected.size > 10 * 1024 * 1024) { setStatus('error'); setError('That file is over 10 MB. Export a lighter PDF and try again.'); return; }
    if (!selected.name.toLowerCase().endsWith('.pdf') && selected.type !== 'application/pdf') { setStatus('unsupported'); setError('DOCX extraction is not available in this browser-only MVP. Export your resume as a PDF and try again.'); return; }
    setStatus('reading');
    try { await new Promise((resolve) => window.setTimeout(resolve, 450)); const text = await extractPdfText(selected); const analyzed = analyzeResume(text, nextMeta); setResult(analyzed); setStatus('ready'); localStorage.setItem(STORAGE_KEY, JSON.stringify(analyzed)); }
    catch (caught) { setStatus('error'); setError(caught instanceof Error ? caught.message : 'We could not read this PDF. Try exporting a fresh text-based PDF.'); }
  };
  const inputChange = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (selected) void processFile(selected); event.target.value = ''; };
  const clear = () => { setFile(null); setMeta(null); setResult(null); setError(null); setStatus('idle'); };
  const retry = () => file ? void processFile(file) : pick();
  return <div className="stagger space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Resume studio / analyzer</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Make your first good impression.</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">A focused read on the resume you have today — what already lands, what gets lost, and the next edit worth making.</p></div><Link href="/soft-skills" className="button-secondary"><Target size={15} /> Soft skills</Link></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#287d78]" /> Runs locally in your browser</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-accent" /> Specific, not generic feedback</span></div>{!meta ? <UploadBox onPick={pick} onDrop={(event) => { const selected = event.dataTransfer.files?.[0]; if (selected) void processFile(selected); }} /> : <FileStatus meta={meta} status={status} error={error} onReplace={clear} onRetry={retry} />}<input ref={inputRef} type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="hidden" onChange={inputChange} data-testid="input-resume-file" />{result ? <Results result={result} onReplace={clear} onReanalyze={retry} /> : !meta && <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border bg-card p-4"><p className="font-mono text-[10px] text-primary">01 / READ</p><p className="mt-2 text-sm font-semibold">We map your signal</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Skills, evidence, structure, and the details a human scan looks for.</p></div><div className="rounded-lg border border-border bg-card p-4"><p className="font-mono text-[10px] text-primary">02 / SCORE</p><p className="mt-2 text-sm font-semibold">We show the why</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">No mystery number — see exactly what moves your readiness score.</p></div><div className="rounded-lg border border-border bg-card p-4"><p className="font-mono text-[10px] text-primary">03 / PRACTICE</p><p className="mt-2 text-sm font-semibold">You leave with a rep</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Three edits, ordered by leverage, so momentum has somewhere to go.</p></div></div>}</div>;
}